Fix property substitution for `PatternResolver`
apache/logging-log4j2 pull request #2667
Opened 2024-06-17 08:51 UTC by vy

Fixes #2666.

2024-06-17 10:03 UTC, ppkarwasz reviewed
I am not really convinced that this is the right approach.

There are two ways to provide an event template to JTL:

1. You can inline the event template in the configuration file using the `eventTemplate` property (of type `String`). Since the template is inlined, property substitution **will occur** before control is passed to JTL. In this case JTL should **not** perform property substitution.

   Note that property substitution on the `eventTemplate` attribute does not guarantee that the result will be a valid JSON document.

   As far as I can see this is the only case you test.

3. You can provide an `eventTemplateUri` property and JTL will retrieve the value itself.
This is the case, when property substitution **should** be applied, possibly in JSON-safe way.

2024-06-17 10:10 UTC, ppkarwasz commented
Using the features currently provided by `PluginBuilder` a possible alternative approach to introduce lookups in event templates would be:

1. Replace the `@PluginAttribute(value = "eventTemplate")` annotation with `@PluginValue(value = "eventTemplate", substitute = false)` to prevent `PluginBuilder` from expanding the lookups in an inlined event template.
2. Apply property substitution manually to the event template in a JSON-safe way.

2024-06-18 07:58 UTC, vy commented
@ppkarwasz, as discussed and agreed on,

1. Added `substitute` flag to `@Plugin[Builder]Attribute`
2. Disabled [configuration file] property substitution for `eventTemplate`, `stackTraceTemplate`, and `EventTemplateAdditionalField#value` attributes

Could you review again, please?

2024-06-18 10:50 UTC, ppkarwasz approved these changes
Looks good to me, but I still find the usage of `StrSubstitutor` a little bit incoherent.

If you use lookups in literals they are expanded at **each** log event, e.g.:

```json
{
  "timestamp": "${date:hh:mm:ss.SSS}"
}
```

but if you wrap it into a `PatternResolver` it is also expanded at configuration time and requires escaping:

```json
{
  "timestamp": {
    "$resolver": "pattern",
    "pattern": "$${date:hh:mm:ss.SSS}"
  }
}
```

2024-06-18 11:28 UTC, vy commented on log4j-layout-template-json/src/main/java/org/apache/logging/log4j/layout/template/json/resolver/PatternResolver.java
> +        return substitutionNeeded ? substitutor.replace(null, pattern) : pattern;
Removed in 03993a8eebfb88617d0c602781b07d7e3e05e41b.

2024-06-19 12:22 UTC, ppkarwasz requested changes

2024-06-19 12:22 UTC, ppkarwasz commented on log4j-layout-template-json/src/main/java/org/apache/logging/log4j/layout/template/json/resolver/TemplateResolverContext.java
> +public interface TemplateResolverContext<V, C extends TemplateResolverContext<V, C>> {
Is this still needed?

2024-06-19 12:22 UTC, ppkarwasz commented on log4j-layout-template-json/src/main/java/org/apache/logging/log4j/layout/template/json/resolver/package-info.java
> +@Version("2.21.0")
... if not, this change can also be reverted.

2024-06-19 12:46 UTC, merged