feat: lock feature by properties(PropertiesPropertySource order in properties)
apache/logging-log4j2 pull request #637
Opened 2021-12-17 11:33 UTC by qxo

so we can change the load order if we need:
such as lock some properties for force disable some feature we don't need.

ie:

SystemPropertiesPropertySource is priority=100, if we want log4j2.component.properties lock some properties(such as log4j2.enableJndi)
that we do not want to be changed by system properties or ENV.
with this feature, log4j2.component.properties as below:
```
log4j2.enableJndi=false
log4j.properties_load_priority=1000
```
Our app do not need jndi lookup feature, so we want force disable it(Can't enable by -Dlog4j2.enableJndi=true or by ENV)

2021-12-24 13:30 UTC, vy requested changes
Thanks so much for your contribution @qxo. I liked the idea, though I would appreciate it if you can create a JIRA ticket and prefix the PR title with the JIRA ticket ID. Once the JIRA ticket is created, other maintainers can weigh in too.

There are also some other stuff that needs to be addressed:

- `changes.xml` update
- tests
- docs

But these can wait for later.

2021-12-24 13:30 UTC, vy commented on log4j-api/src/main/java/org/apache/logging/log4j/util/PropertiesPropertySource.java
> +    private static final String KEY_PRIORITY = "log4j2.properties_load_priority";
```suggestion
    private static final String KEY_PRIORITY = "log4j2.propertySourcePriority";
```

2021-12-24 13:30 UTC, vy commented on log4j-api/src/main/java/org/apache/logging/log4j/util/PropertiesPropertySource.java
> +        final String order = (String)properties.get(KEY_PRIORITY);
Log4j has a fuzzy matching strategy, I am not sure if we can simply look for `KEY_PRIORITY` at this stage – the fuzzy key alternatives might not have been populated.

2023-02-28 15:02 UTC, closed without merging

2023-03-01 07:03 UTC, ppkarwasz commented
This was closed automatically by Github because we renamed the `release-2.x` branch to `2.x`. Feel free to resubmit to the `2.x` branch.